spring:
  application:
    name: micro-epay-mall-client-zuul
  
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

#这里的配置表示，访问/city/** 直接重定向到service-id为micro-various-api-data-weather-city-eureka-feign的微服务下        
zuul:
  routes:
    user:
      path: /epay-mall/user/**
      service-id: micro-epay-mall-user-eureka-feign
